// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjqoDGN6e7vXKiPNUHQWppw7j6rapqa8',
    appId: '1:604650316142:web:7044f9d45a21287a18217f',
    messagingSenderId: '604650316142',
    projectId: 'note-fire-ff273',
    authDomain: 'note-fire-ff273.firebaseapp.com',
    storageBucket: 'note-fire-ff273.appspot.com',
    measurementId: 'G-RKBBBE9YM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGz7P5lfsH4FgpFuPR97g1NLMwPfxCDs',
    appId: '1:604650316142:android:25d046d8e516144e18217f',
    messagingSenderId: '604650316142',
    projectId: 'note-fire-ff273',
    storageBucket: 'note-fire-ff273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNC3wkDYe9JOAMVz8Pg903g-l941I4vBo',
    appId: '1:604650316142:ios:03dc70dad99c70d318217f',
    messagingSenderId: '604650316142',
    projectId: 'note-fire-ff273',
    storageBucket: 'note-fire-ff273.appspot.com',
    iosBundleId: 'com.example.firebaseSend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNC3wkDYe9JOAMVz8Pg903g-l941I4vBo',
    appId: '1:604650316142:ios:0e974943005e242918217f',
    messagingSenderId: '604650316142',
    projectId: 'note-fire-ff273',
    storageBucket: 'note-fire-ff273.appspot.com',
    iosBundleId: 'com.example.firebaseSend.RunnerTests',
  );
}
